name: microservice1
version: 0.1.0
description: A Helm chart for Kubernetes deployment of microservice1
type: application
maintainers:
  - name: Your Name
    email: your.email@example.com
keywords:
  - microservice
  - helm
  - kubernetes
dependencies: []