services:
  frontend: nginx:latest
  backend: nginx:latest
  database: nginx:latest

# Adicionando configuração de réplicas para o serviço backend
backend:
  replicas: 3

config:
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
