services:
  frontend:
    image: nginx:latest
    replicas: 1
  backend: 
    image: nginx:latest
    replicas: 1
  database: 
    image: nginx:latest
    replicas: 1

# Adicionando referência a um microserviço externo
dependencies:
  JJ-pastor:
    enabled: true
    repository: "https://zumtobellighting.github.io/service_1"
    name: "JJ-pastor"
    version: "1.0.0"
    chart: "chart/JJ-pastor"  # Add this line to specify the chart location
    values:
      environment: "dev"
      replicas: 2

config:
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
