services:
  service1:
    image:
      replicas: 2
      repository: nginx
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
  service2:
    image:
      replicas: 1
      repository: nginx
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

config:
  VARIAVEL_GLOBAL: "dev-mode"