apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
{{- range $key, $value := .Values.labels }}
    "{{ $key }}": "{{ $value }}"
{{- end }}
spec:
  ports:
{{- include "ports.service" . | indent 2 }}
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
