microservices:
  microservice1:
    image:
      repository: nanajanashia/argocd-app
      tag: 1.1
    replicas: 5
    service:
      type: ClusterIP
      port: 8080
env:
  # regular variables - can be committed
  regular:
    - name: ENV
      value: "JORGE"
    - name: DB_HOST
      value: "PASTOR"
    - name: DB_PORT
      value: "5432"    

# Additional microservices can be added here with their respective configurations.