apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dev
spec:
  selector:
    matchLabels:
      app: myapp-dev
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp-dev
    spec:
      containers:
      - name: myapp-dev
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
