apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-product-helm-chart.fullname" . }}
  labels:
    {{- include "my-product-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-product-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-product-helm-chart.name" . }}
    spec:
      containers:
      - name: {{ include "my-product-helm-chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}