apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-product-helm-chart.fullname" . }}
  labels:
    {{- include "my-product-helm-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-product-helm-chart.name" . }}