apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-go-app
  labels:
    app: {{ .Release.Name }}-my-go-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-my-go-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-my-go-app
    spec:
      containers:
        - name: my-go-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}