service-hello:
  replicaCount: 1
  serviceAccount:
    create: true
  ingress:
    enabled: false
  autoscaling:
    enabled: false
service-hello-1:
  replicaCount: 1
  serviceAccount:
    create: true
  ingress:
    enabled: false
  autoscaling:
    enabled: false
