environment: staging

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: staging-api.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: LOG_LEVEL
    value: "info"
  - name: ENV
    value: "staging"
