apiVersion: v2
name: my-product-helm-chart
description: A Helm chart for deploying my product microservices
type: application
version: 1.0.0
appVersion: "1.0.0"

replicaCount: 5

image:
  repository: nanajanashia/argocd-app
  pullPolicy: IfNotPresent
  tag: "1.2"

service:
  enabled: true
  name: myapp-qa
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  name: ""
  path: /
  pathType: ImplementationSpecific
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: [] 

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}