name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Adicione esta linha

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Use tag as version if available
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # Generate version based on commit hash
            VERSION=$(git describe --tags --always --dirty)-$(date +'%Y%m%d%H%M%S')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set lowercase image name
        run: |
          IMAGE_NAME_LC=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LC=$IMAGE_NAME_LC" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::449750626230:role/GithubActionECRPush
            aws-region: eu-central-1
            audience: sts.amazonaws.com 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
            
      - name: Update Helm chart image tag
        if: github.event_name != 'pull_request'
        run: |
          # Update the image tag in the Helm values file
          sed -i "s|tag: .*|tag: \"${{ env.VERSION }}\"|" ./helm/values.yaml
          
          # Optionally commit and push the changes if you have the right permissions
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add ./helm/values.yaml
            git commit -m "Update Helm chart image tag to ${{ env.VERSION }}"
            git push
