apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-qa
spec:
  selector:
    matchLabels:
      app: myapp-qa
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-qa
    spec:
      containers:
      - name: myapp-qa
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
